name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  build-test:
    name: Lint • Typecheck • Test • Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Vitest)
        run: npm run test

      - name: Build (Vite)
        run: npm run build

      # (opzionale) conserva la build come artifact
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
