name: CI (lint • typecheck • test • build • gated prod deploy)

on:
  pull_request:
    branches: [main] # CI sulle PR verso main (no deploy)
  push:
    branches: [main] # CI + Deploy Hook SOLO su main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint • Typecheck • Test • Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Vitest)
        run: npm run test

      - name: Build (Vite)
        run: npm run build

      # Opzionale: conserva l'artefatto di build
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy_production:
    name: Trigger Vercel PRODUCTION
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Production Deploy Hook
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_PROD }}"
