name: CI (lint • typecheck • test • build • gated deploy)

on:
  pull_request:
    branches: [main] # PR verso main
  push:
    branches: [main] # push su main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint • Typecheck • Test • Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test (Vitest)
        run: npm run test

      - name: Build (Vite)
        run: npm run build

      # Facoltativo: conserva la build
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy_preview:
    name: Trigger Vercel PREVIEW
    needs: ci
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Preview Deploy Hook
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_PREVIEW }}"

  deploy_production:
    name: Trigger Vercel PRODUCTION
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Production Deploy Hook
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_PROD }}"
